name: Deploy static site

on:
  push:
    branches: ["main"]

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .   # publica lo que está en la raíz (incluye index.html)
      - id: deployment
        uses: actions/deploy-pages@v4
