<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Privacy Policy</title>
</head>
<body>
    <h1>Pacerunner Privacy Policy</h1>
    <p><strong>Type of website:</strong> Running App</p>
    <p><strong>Effective date:</strong> 20th day of October, 2024</p>

    <p>Pacerunner is owned and operated by Francisco Orta Bazán. Francisco Orta Bazán can be contacted at:</p>
    <ul>
        <li>Email: pacerunner1@gmail.com</li>
        <li>Phone: (956) 561-6125</li>
        <li>Address: 3404 Beacon St</li>
    </ul>

    <h2>Purpose</h2>
    <p>The purpose of this privacy policy (this "Privacy Policy") is to inform users of our Site of the following:</p>
    <ol>
        <li>The personal data we will collect;</li>
        <li>Use of collected data;</li>
        <li>Who has access to the data collected;</li>
        <li>The rights of Site users.</li>
    </ol>
    <p>This Privacy Policy applies in addition to the terms and conditions of our Site.</p>

    <h2>Consent</h2>
    <p>By using our Site, users agree that they consent to:</p>
    <ol>
        <li>The conditions set out in this Privacy Policy; and</li>
        <li>The collection, use, and retention of the data listed in this Privacy Policy.</li>
    </ol>

    <h2>Personal Data We Collect</h2>
    <h3>Data Collected Automatically</h3>
    <p>When you visit and use our Site, we may automatically collect and store the following information:</p>
    <ul>
        <li>Location.</li>
    </ul>

    <h3>Data Collected in a Non-Automatic Way</h3>
    <p>We may also collect the following data when you perform certain functions on our Site:</p>
    <ul>
        <li>Email address.</li>
    </ul>
    <p>This data may be collected using the following methods:</p>
    <ul>
        <li>Creating an account.</li>
    </ul>

    <h2>How We Use Personal Data</h2>
    <p>Data collected on our Site will only be used for the purposes specified in this Privacy Policy or indicated on the relevant pages of our Site. We will not use your data beyond what we disclose in this Privacy Policy.</p>
    <p>The data we collect automatically is used for the following purposes:</p>
    <ul>
        <li>Statistics.</li>
    </ul>
    <p>The data we collect when the user performs certain functions may be used for the following purposes:</p>
    <ul>
        <li>Communication.</li>
    </ul>

    <h2>Who We Share Personal Data With</h2>
    <h3>Employees</h3>
    <p>We may disclose user data to any member of our organization who reasonably needs access to user data to achieve the purposes set out in this Privacy Policy.</p>

    <h3>Other Disclosures</h3>
    <p>We will not sell or share your data with other third parties, except in the following cases:</p>
    <ul>
        <li>If the law requires it;</li>
        <li>If it is required for any legal proceeding;</li>
        <li>To prove or protect our legal rights; and</li>
        <li>To buyers or potential buyers of this company in the event that we seek to sell the company.</li>
    </ul>
    <p>If you follow hyperlinks from our Site to another Site, please note that we are not responsible for and have no control over their privacy policies and practices.</p>

    <h2>How Long We Store Personal Data</h2>
    <p>User data will be stored until the purpose the data was collected for has been achieved. You will be notified if your data is kept for longer than this period.</p>

    <h2>How We Protect Your Personal Data</h2>
    <p>At Pacerunner, we are committed to protecting the privacy and security of our users’ data. We have implemented the following measures to ensure that any personal data collected is handled with the utmost care:</p>
    <ul>
        <li><strong>Data Encryption:</strong> All data transmitted between the app and our servers is encrypted using HTTPS (SSL/TLS) protocols to prevent unauthorized access during transmission.</li>
        <li><strong>Firebase Security:</strong> We use Google Firebase to store and manage data, which complies with industry-standard security practices. Firebase automatically encrypts data at rest and during transit.</li>
        <li><strong>Authentication and Access Control:</strong> Only authorized individuals have access to user data, and we implement role-based access controls to limit exposure to sensitive information.</li>
        <li><strong>Regular Security Audits and Monitoring:</strong> We monitor our systems regularly to detect and prevent unauthorized access. Any security incidents are immediately investigated and addressed.</li>
        <li><strong>User Control over Data:</strong> Users have control over their data and can request its deletion or modification by contacting us at any time.</li>
        <li><strong>Compliance with Standards:</strong> We follow the relevant data protection regulations, including GDPR (for European users) and CCPA (for California users), to ensure transparency and safeguard user privacy.</li>
    </ul>
    <p>While we take all reasonable precautions to ensure that user data is secure and that users are protected, there always remains the risk of harm. The Internet as a whole can be insecure at times, and therefore we are unable to guarantee the security of user data beyond what is reasonably practical.</p>

    <h2>Children</h2>
    <p>We do not knowingly collect or use personal data from children under 13 years of age. If we learn that we have collected personal data from a child under 13 years of age, the personal data will be deleted as soon as possible. If a child under 13 years of age has provided us with personal data, their parent or guardian may contact our privacy officer.</p>

    <h2>How to Access, Modify, Delete, or Challenge the Data Collected</h2>
    <p>If you would like to know if we have collected your personal data, how we have used your personal data, if we have disclosed your personal data, and to whom we disclosed your personal data, or if you would like your data to be deleted or modified in any way, please contact our privacy officer here:</p>
    <ul>
        <li>Francisco Orta Bazán</li>
        <li>Email: pacerunner1@gmail.com</li>
        <li>Phone: (956) 561-6125</li>
        <li>Address: 3404 Beacon Court</li>
    </ul>

    <h2>Do Not Track Notice</h2>
    <p>Do Not Track ("DNT") is a privacy preference that you can set in certain web browsers. We do not track the users of our Site over time and across third-party websites and therefore do not respond to browser-initiated DNT signals.</p>

    <h2>Modifications</h2>
    <p>This Privacy Policy may be amended from time to time to maintain compliance with the law and reflect any changes to our data collection process. When we amend this Privacy Policy, we will update the "Effective Date" at the top of this Privacy Policy. We recommend that users periodically review our Privacy Policy to ensure that they are notified of any updates. If necessary, we may notify users by email of changes to this Privacy Policy.</p>

    <h2>Contact Information</h2>
    <p>If you have any questions, concerns, or complaints, you can contact our privacy officer, Francisco Orta Bazán, at:</p>
    <ul>
        <li>Email: pacerunner1@gmail.com</li>
        <li>Phone: (956) 561-6125</li>
        <li>Address: 3404 Beacon Court</li>
    </ul>

    <footer>
        <p>Pacerunner Chase Your Pace - 2024</p>
    </footer>
</body>
</html>
